# Generated by Django 3.1.1 on 2020-12-06 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_contacts_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
