# Generated by Django 3.1.1 on 2021-01-21 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_auto_20201206_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sender', to='messenger.user'),
            preserve_default=False,
        ),
    ]
